#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0

"""
Parser for DAMON data files generated by damo record command
"""

import csv
import json
import os
import sys

# Add damo source path to Python path to import damo modules
repo_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..'))
damo_src_path = os.path.join(repo_path, 'damo', 'src')
if damo_src_path not in sys.path:
    sys.path.insert(0, damo_src_path)

# Import damo modules for record parsing
try:
    # First import main damo module which sets up the path correctly
    import damo
    # Now we can import internal modules through damo's path setup
    # Since damo.py sets up the path correctly, we can import _damo_records
    import _damo_records
    import _damon
    import _damo_fmt_str
    print("Successfully imported damo modules")
except ImportError as e:
    print(f"Failed to import damo modules: {e}")
    sys.exit(1)

def parse_damon_data_file(file_path):
    """
    Parse a damon.data file and return the records
    
    Args:
        file_path (str): Path to the damon.data file
        
    Returns:
        tuple: (records, error) where records is the parsed data and error is None if successful
    """
    if not os.path.exists(file_path):
        return None, f"File {file_path} does not exist"
    
    try:
        # Use the parse_records_file function from _damo_records
        # This is imported through the damo module's path setup
        records, error = _damo_records.parse_records_file(file_path)
        if error:
            return None, error
        return records, None
    except Exception as e:
        return None, f"Error parsing file {file_path}: {e}"


def _parse_int_from_text(text):
    """Convert numbers like "1,000" or "1000" to int, fallback to 0."""
    try:
        if isinstance(text, int):
            return text
        if not isinstance(text, str):
            return 0
        cleaned = text.replace(',', '').split()[0]
        return int(cleaned)
    except Exception:
        return 0


def parse_max_regions_from_kdamonds(kdamonds_path):
    """Read damon.data.kdamonds to obtain max nr_regions; return (int, error)."""
    if not os.path.exists(kdamonds_path):
        return None, f"File {kdamonds_path} does not exist"

    try:
        with open(kdamonds_path, 'r') as f:
            data = json.load(f)
        if not data:
            return None, f"No content in {kdamonds_path}"
        entry = data[0]
        contexts = entry.get('contexts', [])
        if not contexts:
            return None, f"No contexts in {kdamonds_path}"
        nr_regions = contexts[0].get('nr_regions', {})
        max_regions = _parse_int_from_text(nr_regions.get('max', 0))
        if max_regions <= 0:
            return None, f"Invalid nr_regions.max in {kdamonds_path}"
        return max_regions, None
    except Exception as e:
        return None, f"Failed to parse {kdamonds_path}: {e}"


def _region_fields(region):
    """Extract size, start, nr_accesses, age from a region with fallbacks."""
    size_bytes = region.size() if hasattr(region, 'size') else 0
    start_addr = getattr(region, 'start', 0)

    nr_accesses_val = 0
    if getattr(region, 'nr_accesses', None):
        if hasattr(region.nr_accesses, 'samples') and region.nr_accesses.samples is not None:
            nr_accesses_val = region.nr_accesses.samples
        elif hasattr(region.nr_accesses, 'percent') and region.nr_accesses.percent is not None:
            nr_accesses_val = region.nr_accesses.percent

    age_val = 0
    if getattr(region, 'age', None):
        if hasattr(region.age, 'usec') and region.age.usec is not None:
            age_val = region.age.usec
        elif hasattr(region.age, 'aggr_intervals') and region.age.aggr_intervals is not None:
            age_val = region.age.aggr_intervals

    return size_bytes, start_addr, nr_accesses_val, age_val


def write_snapshots_to_csv(records, max_regions, output_file):
    """Write all snapshots to CSV with fixed columns per snapshot."""
    if max_regions <= 0:
        raise ValueError("max_regions must be positive")

    header = ["start_time_ns", "end_time_ns"]
    for idx in range(max_regions):
        header.extend([
            f"region_{idx}_size_bytes",
            f"region_{idx}_start",
            f"region_{idx}_nr_accesses",
            f"region_{idx}_age"
        ])

    with open(output_file, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(header)

        for record in records:
            for snapshot in record.snapshots:
                row = [snapshot.start_time, snapshot.end_time]
                regions = snapshot.regions if snapshot.regions else []
                for region in regions[:max_regions]:
                    row.extend(_region_fields(region))
                # pad remaining regions with zeros
                missing = max_regions - len(regions)
                if missing > 0:
                    row.extend([0] * (missing * 4))
                writer.writerow(row)

def main():
    """
    Main function to demonstrate damon.data file parsing
    """
    # Check if correct number of arguments provided
    if len(sys.argv) != 3:
        print("Usage: python3 damon.data.py <input_file> <output_file>")
        print("  <input_file>: Path to damon.data file")
        print("  <output_file>: Path to output analysis results")
        return 1
    
    input_path = sys.argv[1]
    output_path = sys.argv[2]

    damon_data_filename = "damon.data"
    input_file = os.path.join(input_path, damon_data_filename)

    output_file_name = "damon_data.csv"
    output_file = os.path.join(output_path, output_file_name)
    kdamonds_file = os.path.join(input_path, "damon.data.kdamonds")
    
    print(f"Parsing DAMON data file: {input_file}")
    print(f"Output will be written to: {output_file}")
    print(f"Reading kdamonds metadata from: {kdamonds_file}")
    
    max_regions, max_err = parse_max_regions_from_kdamonds(kdamonds_file)
    if max_err:
        print(f"Error: {max_err}")
        return 1

    # Parse the damon.data file
    records, error = parse_damon_data_file(input_file)
    
    if error:
        print(f"Error: {error}")
        return 1
    
    if records is None:
        print("No records found")
        return 1
    
    print(f"Successfully parsed {len(records)} records")

    try:
        write_snapshots_to_csv(records, max_regions, output_file)
    except Exception as e:
        print(f"Error writing CSV: {e}")
        return 1

    print(f"CSV generated: {output_file}")
    
    return 0

if __name__ == "__main__":
    sys.exit(main())